name: Build Windows EXE

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Compile WinAPI EXE
        run: cl main.cpp user32.lib gdi32.lib

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: rectangle-exe
          path: main.exe
